import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div 
          className='fixed top-0 left-0 w-full h-full bg-gradient-to-br from-pink-400 to-[#0055D1] rounded-md filter blur-sm opacity-50 -z-50'
        />
        {children}
      </body>
    </html>
  );
}
